### PR TITLE
Crop thumbnails

### LINKED ISSUE #735: Homepage when narrow bounces around
When the homepage is narrow, lower content on the page bounces around because carousel content changes height: Audio logos are taller than the thumbnails.

screen shot 2015-09-25 at 12 07 33 pm

### PR DESCRIPTION
**Pull request by mccalluc**
@afred?

Crop all placeholder thumbs: for digitized and other `convert $_ -crop 300x225+0+52 $_`; for undigitized +72 to fit the extra line. 

Fix #735. In context:
screen shot 2015-11-05 at 2 54 52 pm

### CODE REVIEW

**Comment by afred** [comment]
:+1: from me. Is this ok @caseyedavis12? Look at the [files changed](https://github.com/WGBH/AAPB2/pull/832/files)

**Comment by caseyedavis12** [comment]
@afred and @mccalluc: looks good to me. Can you confirm that the cropped version still looks OK on the homepage in desktop mode?

**Comment by afred** [comment]
Here is what it looks like currently...
image

Here is with the change...
image

**Comment by caseyedavis12** [comment]
@afred: sorry to be nit-picky, but it looks like the changed version looks a little blurry compared to the original version.


cc @mccalluc

**Comment by afred** [comment]
@caseyedavis12, yeah I noticed that too. It has been enlarged because the carousel style stretches the images vertically to fill the space of a single carousel item. The same style is applied to the video thumbs, but i guess it's less noticeable since they are not sharp icons.

The carousel comes pre-packaged for us, so breaking it open to tweak the styles is likely to be trickier than it looks.

@mccalluc ideas?

**Comment by afred** [comment]
@mccalluc actually, since the featured thumbnail URLs are hard coded, we could just make a sharper 4:3 img that will fill space on desktop screens without getting blurry, and use those in `config/featured/home-featured.yml`

Or we could them all into SVG and worry about resizing no more

**Comment by mccalluc** [comment]
- I always enjoy making gratuitous SVGs.
- We can ask Mike H if he can give us a higher resolution file.
- Originals were JPG, and compression artifacts were visible: Color shift near edge of contrasting squares. PNG would be better.

@afred?

**Comment by afred** [comment]
@mccalluc I'm :+1: for any of those options. Your call.

**Comment by caseyedavis12** [comment]
@mccalluc: let me know if you want me to contact Hilary and Mike about png or larger versions.

**Comment by afred** [comment]
@mccalluc emailed @Hammicakes and we're waiting for a response.

**Comment by caseyedavis12** [comment]
@afred: I followed up with Hilary (the Digital Project Manager) to see if she was going to be able to fit this into Mike Hamilton's schedule this week. If his schedule is booked, we should have a back-up plan so that we can redeploy this week without the svg versions (and without fuzzy thumbnails).


cc @mccalluc

**Comment by afred** [comment]
@caseyedavis12 @mccalluc.

We are unable to get non-fuzzy 4:3 thumbnails within a couple of hours, then we need to decide whether we want this commit or not:
  1. **Merge the commit**
    - Fixes the "jumping" effect of content below the carousel when browser is narrow. Does not jump much, but makes reading content hard.
    - Generic thumbs on homepage carousel are blurry; not much, but noticeable.
  1. **Don't merge the commit**
    - The "jumping" effect continues when browser is in narrow view.
    - Generic thumbs on homepage carousel are not blurry.
  

@caseyedavis12 elects option #2, citing analytics that indicate low mobile usage at this time.

Keeping this PR open, but moving it to the next milestone.

**Comment by mccalluc** [comment]
@afred: Do we want to re-request the images? Or make our own svgs?

**Comment by afred** [comment]
@mccalluc how much work to make SVGs?

**Comment by caseyedavis12** [comment]
@afred and @mccalluc: We're very, very low on developer funds for the AAPB at this point, unfortunately. Can you hold off on doing AAPB work until we re-prioritize for the January redeploy?

**Comment by mccalluc** [comment]
@caseyedavis12 : If you want this to happen, you need to ping Mike and get him to deliver higher resolution and/or vector.

**Comment by mccalluc** [comment]
@caseyedavis12 : What do you want to happen with this? I won't repeat the whole thread, but one of
- good enough
- get vectors from design
- chuck makes SVG

**Comment by caseyedavis12** [comment]
@mccalluc: Good enough.

**Comment by mccalluc** [comment]
@afred?

**Pull request merged**
