### PR TITLE
1078: Device Independent Control

### LINKED ISSUE #1078: Device independent control should be consistent
Device independent control on the AAPB website should be consistent. Currently, some focus is a default dotted box that is not very visible. Some focus is a more defined blue box.

### PR DESCRIPTION
**Pull request by jasoncorum**
@afred - This ups the contrast when tabbing through the site links per the NCAM recommendations. Tested in Chrome, Safari and Firefox. Closes #1078

### CODE REVIEW

**Comment by jasoncorum** [comment]
@afred - actually hold on this one. found a tiny bit of weird behavior. this will also close #1079

**Comment by jasoncorum** [comment]
@afred - This should be good to go now.

**Comment by afred** [comment]
@jasoncorum had to rebase onto `master` and fix a conflict in `app/assets/stylesheets/locals/carousel.css.scss`. It had to do with bringing in `.blacklight-home .list-group-item` at the bottom of the stylesheet. Confirm that we want it?

**Comment by jasoncorum** [comment]
@afred - So I pulled back the code on this to give it a quick test. Tabbing through the carousel doesn't highlight the additional/new controls. Can you hold on merging and I'll take a look first thing on Monday.

**Comment by afred** [comment]
np

**Comment by jasoncorum** [comment]
@afred - OK. This should be good to go now!

**Pull request merged**
