### PR TITLE
Orr privs

### PR DESCRIPTION
**Pull request by afred**

### CODE REVIEW

**Comment by afred** [comment]
@mccalluc does this failure ring a bell?

**Comment by mccalluc** [comment]
So the fix is to remove the 
```diff
       -  <pbcoreRightsSummary>
       -    <rightsEmbedded>
       -      <AAPB_RIGHTS_CODE>ON_LOCATION_ONLY</AAPB_RIGHTS_CODE>
       -    </rightsEmbedded>
       -  </pbcoreRightsSummary>
```
from clean-basic.xml: That is no longer how we express privs. (Why it's here now, presuming I had left it in a passing state earlier, I don't know.)

**Comment by afred** [comment]
yeah.. the diff shows that chunk getting removed from all other fixtures.. just not `clean-basic.xml`. Willing to ignore the mystery for now, and just fix it. Stand by...

**Comment by afred** [comment]
@mccalluc so... what should `clean-basic.xml` look like? I currently have this:
```xml
<pbcoreDescriptionDocument xsi:schemaLocation='http://www.pbcore.org/PBCore/PBCoreNamespace.html http://www.pbcore.org/xsd/pbcore-2.0.xsd' xmlns='http://www.pbcore.org/PBCore/PBCoreNamespace.html' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
  <!-- Root attributes are screwy in AMS export. -->
  <pbcoreIdentifier source='WERU Prog List'>WRF028</pbcoreIdentifier>
  <pbcoreIdentifier source='http://americanarchiveinventory.org'>cpb-aacip/301-60cvdtx8</pbcoreIdentifier>
  <pbcoreTitle titleType='Program'>WRF-09/13/07</pbcoreTitle>
  <pbcoreTitle titleType='Series'>Writers Forum</pbcoreTitle>
  <pbcoreDescription>No description available</pbcoreDescription>
  <pbcoreCoverage>
    <coverage>mock value which should be preserved</coverage>
    <coverageType>Spatial</coverageType>
  </pbcoreCoverage>
  <pbcoreCoverage>
    <coverage>mock value which should be preserved</coverage>
    <coverageType>Temporal</coverageType>
  </pbcoreCoverage>
  <pbcoreRightsSummary>
    <rightsSummary>There should be only one.</rightsSummary>
  </pbcoreRightsSummary>
  <pbcoreRightsSummary>  </pbcoreRightsSummary>
  <pbcoreRightsSummary>
    <rightsEmbedded>
      <AAPB_RIGHTS_CODE>ON_LOCATION_ONLY</AAPB_RIGHTS_CODE>
    </rightsEmbedded>
  </pbcoreRightsSummary>
  <pbcoreInstantiation>
    <instantiationIdentifier source='WERU Prog List'>WRF028</instantiationIdentifier>
    <instantiationPhysical>CD</instantiationPhysical>
    <instantiationLocation>WERU Archives - CD Shelves</instantiationLocation>
    <instantiationMediaType>Sound</instantiationMediaType>
    <instantiationGenerations>Original</instantiationGenerations>
    <instantiationDuration>00:55:49</instantiationDuration>
  </pbcoreInstantiation>
  <pbcoreAnnotation annotationType='last_modified'>2013-06-03 01:50:55</pbcoreAnnotation>
  <pbcoreAnnotation annotationType='organization'>WERU-FM (WERU Community Radio)</pbcoreAnnotation>
  <pbcoreAnnotation annotationType='Level of User Access'>Online Reading Room</pbcoreAnnotation>
</pbcoreDescriptionDocument>
```

**Comment by afred** [comment]
@mccalluc specifically it seems odd that this would be in the "clean" version:
```xml
```

**Comment by mccalluc** [comment]
@afred : Sorry if I'm missing the point, but it looks like you still have 
```
  <pbcoreRightsSummary>
    <rightsEmbedded>
      <AAPB_RIGHTS_CODE>ON_LOCATION_ONLY</AAPB_RIGHTS_CODE>
    </rightsEmbedded>
  </pbcoreRightsSummary>
```
in there. Remove it, and the diff error you get from tests should go again.

**Comment by mccalluc** [comment]
This:
```
<pbcoreRightsSummary>  </pbcoreRightsSummary>
```
is a result of the new code that removes duplicated elements... but it doesn't go up to removing the parents. I think this is fine for now.

**Comment by afred** [comment]
ah.. yes.. last comment clarifies. Thanks.

**Pull request merged**
