### PR TITLE
Create static orr-rules

### PR DESCRIPTION
**Pull request by caseyedavis12**
Legal counsel wanted a static ORR Rules page to appear with the other Legal Pages (Privacy and TOU) in the footer. If there is a better way to do this with the existing show.md please let me know. This version does not need the "I accept" at the bottom since it is just to provide users a link to this documentation.

### CODE REVIEW

**Comment by afred** [comment]
@caseyedavis12 is this supposed to be linked from somewhere?

**Comment by afred** [comment]
@caseyedavis12 made some adjustments. Look ok?

image

**Comment by mccalluc** [comment]
Hold on: This is just a copy and paste of the ORR rules, right? We shouldn't copy and paste anything anything as complex as this: It will certainly get out of sync over time. Requirements:
- New link in footer: "ORR Rules of Use". @caseyedavis12 : ok?
- Link to "/terms", which is the same as "terms/1234" except no ok button at the bottom, and a sidebar to the side.

Implementation:
- move text from `terms/show.erb` to `override/legal/orr-rules-of-use.md`.
- `terms/show.erb` is much simpler, and pulls in the override content
- add a footer link.

@afred: Do you have something in progress?

**Comment by caseyedavis12** [comment]
Hi Drew,


Yes, I copied and pasted everything except for the code at the bottom of the original show.md.


Your plan works. New link in footer that says "ORR Rules of Use" above Terms and Privacy. It will link to /terms with no button at the bottom.


Best,

Casey

________________________________

**Comment by afred** [comment]
@mccalluc ah.. i thought this was entirely new content, didn't realize it already existed in `terms/show.erb`. I saw that casey had copy and pasted from somewhere, and all I did was turn it into proper markdown. I don't have anything currently in progress here

**Comment by mccalluc** [comment]
@afred: review. Thanks!

**Pull request merged**
