### PR TITLE
Update catalog_controller.rb

### PR DESCRIPTION
**Pull request by Muraszko**

### CODE REVIEW

**Comment by afred** [comment]
@Muraszko did you get the test to pass?

**Comment by Muraszko** [comment]
No, but the only change was text.
When I removed the Ci script directory this morning (before I put it back) I was hoping that was what was throwing the tests off but it wasn't the case, it still failed:
https://travis-ci.org/WGBH/AAPB2/builds/161623824

**Comment by afred** [comment]
The failing test is one that is checking for specific text. You change the text, you need to change the test as well.

This isn't the best way to test this type of thing, for exactly this reason. But I think we still want all the tests to be green. I'll take a quick peek.

**Comment by Muraszko** [comment]
@afred Ahh, that makes sense. Yes, green tests would be good. Thank you!

**Pull request merged**
