### PR TITLE
adds wnet history

### PR DESCRIPTION
**Pull request by sroosa**

### CODE REVIEW

**Comment by sroosa** [comment]
@mccalluc Will you check that I formatted it correctly in the .yml. I tried to copy what we did with the other stations history, but the text seems like it's wrapping weirdly. Thanks!

**Comment by mccalluc** [comment]
Rebase might help with tests?

**Comment by mccalluc** [comment]
@sroosa : I've loaded it locally, and the long lines cause no problems in display. I'll put the manual line wraps in there, but there's nothing special about it: just hit return.

**Comment by mccalluc** [comment]
Remaining test failures after rebase are related to #949, and are unrelated to PR.

**Pull request merged**
