### PR TITLE
Fix broken affixed navigation.

### LINKED ISSUE #611: Floating Navigation on homepage
@Hammicakes: we have deployed the floating navigation to demo.americanarchive.org.

When I first come to the website, the floating navigation works great. But if I go to another page on the website and then come back to the homepage, the floating navigation does not appear.

### PR DESCRIPTION
**Pull request by afred**
* Adds jquery-turbolinks gem, which, resolves issues with jquery events not
  firing due to turbolinks black magic.
* Requires changing the event to which Affix plugin is applied.
* Closes #611.

### CODE REVIEW

**Comment by afred** [comment]
@mccalluc?

**Comment by mccalluc** [comment]
@afred: This needs to be rebased on top of your other header PR in order to see it in action, right? I'm not seeing it right now. (Do we want to go on with this now, or would we like to experiment with turning it entirely off first?)

**Comment by afred** [comment]
@mccalluc I don't think it needs rebased. You _do_ need to restart rails though

**Comment by afred** [comment]
@mccalluc ok.. I'm now seeing what I assume to be the same brokenness. Rebasing, stand by.

**Comment by afred** [comment]
@mccalluc? rebased. Looking good on my end.

**Pull request merged**
