### PR TITLE
Genre format 427

### PR DESCRIPTION
**Pull request by mccalluc**
@foo4thought : please review.

### CODE REVIEW

**Comment by mccalluc** [comment]
*WARNING*: This introduces a new facet; We'll need to do a full reindex after merging this or there will be dead links. Alternatively, those parts could be commented out, and leave it for a future PR to uncomment them. Thoughts?

**Comment by afred** [comment]
@caseyedavis12 Do you need to show this feature to anyone in the next two weeks? If not, then I'd prefer to hold off on merging until I finish some of the deployment workflow tasks I have assigned to me.

If you _do_ need it sooner than that, then we can add some patch-work to get it working using current deployment methods.

**Comment by caseyedavis12** [comment]
@afred: I do not need to show this feature to anyone in the next two weeks.

**Comment by mccalluc** [comment]
@afred: should be ready to go, now.

**Pull request merged**
