### PR TITLE
adds new images to gallery

### PR DESCRIPTION
**Pull request by sroosa**
replaces old images, with images for records that will be in the ORR

### CODE REVIEW

**Comment by afred** [comment]
@sroosa all these images are the same?.. i.e. `thumbs/audio-digitized.jpg`?

**Comment by sroosa** [comment]
@afred I put the audio ones at the top and the video ones at the bottom, so that it's easier for me to change them out if I need to. The audio records all have the same image, but the video records each have a unique thumbnail.

**Comment by mccalluc** [comment]
hmm... but is that necessary? I'll check out this branch and see if it still works without those. Hold on...

**Comment by afred** [comment]
@mccalluc @sroosa I guess i'm unclear on why the videos don't have a value for `thumbnail_url`, while the audio does, but they are all the same. Clarification?

**Comment by afred** [comment]
@mccalluc just clarified verbally. Thanks!

**Comment by mccalluc** [comment]
(Talked in person. Waiting to see if Sadie can put the images on S3...)

**Comment by mccalluc** [comment]
@afred : do you have any experience with s3 permissions? Somehow the "casey_davis" user was granted privs; I'd like to do the same for Sadie: I've tried both her user name and ARN... Can you think of something else to try? I've found threads like this that look unhappy: https://forums.aws.amazon.com/thread.jspa?threadID=70876#281141

**Comment by afred** [comment]
@mccalluc i don't. Reading on it now.

just to be clear... we want to allow multiple people to push to a single bucket. Is that the use case?

**Comment by sroosa** [comment]
@mccalluc I just added all of the new images to S3.

**Pull request merged**
