### PR TITLE
Download from popup 950

### PR DESCRIPTION
**Pull request by mccalluc**
@afred / @caseyedavis12 ?

The original request was to download all forms of the transcript. The API provides just one, as far as I can tell, and I guess they generate the others from this? Rather than confusing things downstream, I suggest we just pass through the information PopUp provides to us.

(You'll need to provide the OAuth credentials locally if you want to run this. gitignored.)

No testing on this right now: Combination of simplicity, obvious if failure, question of what layer to test at, etc.

```
$ ruby scripts/popup_archive.rb ~/trans
Chicago Public Radio (WBEZ-FM) and Vocalo.org: 7949
AA1677L5/cpb-aacip-50-29p2nmbv.mp3: 57449
AA1677L5/cpb-aacip-50-29p2nm8g.mp3: 57435
AA1677L5/cpb-aacip-50-2908kt4w.mp3: 57433
AA1677L5/cpb-aacip-50-29p2nm95.mp3: 57436
AA1677L5/cpb-aacip-50-29b5mq7c.mp3: 57434

WGBH: 7818
AA1670L5/cpb-aacip-15-000000009s__barcode339656_.h264.mp4: 57452
AA1670L5/cpb-aacip-15-000000008g__barcode48705_.h264.mp4: 57432
AA1670L5/cpb-aacip-15-0000000075__CBS177-213_.h264.mp4: 57431
AA1670L5/cpb-aacip-15-000000006v__201201T16A_.h264.mp4: 57430
AA1670L5/cpb-aacip-15-000000002m__barcode48704_.h264.mp4: 57429

[AAPB2]$ tree ~/trans
/Users/chuck_mccallum/trans
├── 7818
│   ├── cpb-aacip-15-000000002m__barcode48704_.h264.mp4-entities.json
│   ├── cpb-aacip-15-000000006v__201201T16A_.h264.mp4-entities.json
│   ├── cpb-aacip-15-0000000075__CBS177-213_.h264.mp4-entities.json
│   ├── cpb-aacip-15-000000008g__barcode48705_.h264.mp4-entities.json
│   └── cpb-aacip-15-000000009s__barcode339656_.h264.mp4-entities.json
└── 7949
    ├── cpb-aacip-50-2908kt4w.mp3-entities.json
    ├── cpb-aacip-50-29b5mq7c.mp3-entities.json
    ├── cpb-aacip-50-29p2nm8g.mp3-entities.json
    ├── cpb-aacip-50-29p2nm95.mp3-entities.json
    └── cpb-aacip-50-29p2nmbv.mp3-entities.json
[AAPB2]$ head -n18 ~/trans/7949/cpb-aacip-50-29p2nmbv.mp3-transcript.json 
{
  "language": "en-US",
  "id": 113616,
  "parts": [
    {
      "id": 17607054,
      "text": "You",
      "start_time": "5.74",
      "end_time": "6.93",
      "speaker_id": 400297
    },
    {
      "id": 17607055,
      "text": "thinking discussing and writing. And roman information and shimmers every third weekend program.",
      "start_time": "6.2",
      "end_time": "11.58",
      "speaker_id": 400298
    },
[AAPB2]$ head -n11 ~/trans/7949/cpb-aacip-50-29p2nmbv.mp3-entities.json 
[
  {
    "id": 1356932,
    "name": "Health & Medical & Pharma",
    "is_confirmed": false,
    "identifier": null,
    "score": 1.0,
    "type": null,
    "category": "topic",
    "extra": "{\"original\"=>\"Health_Medical_Pharma\"}"
  },
```

### CODE REVIEW

**Comment by mccalluc** [comment]
(Failures because of SSL.)

**Comment by mccalluc** [comment]
@caseyedavis12 : here is [entities.zip](https://github.com/WGBH/AAPB2/files/238680/entities.zip)

**Comment by caseyedavis12** [comment]
@mccalluc: thank you!

________________________________

**Comment by afred** [comment]
@mccalluc so this downloads everything, but doesn't zip it, correct?

Also, does it make sense for this to live here?

**Comment by mccalluc** [comment]
@afred: "everything" is relative, but yes. There's lots of stuff the API could provide which isn't relevant to us: https://www.popuparchive.com/developer/#!/collections/api_collection_item_get_6

Location: Would you prefer a separate project? It felt like a tool that is being used with AAPB data, so seemed ok to me.

**Comment by afred** [comment]
re: location, this seems an appropriate place. My concern is that is seems a little "admin-y". We haven't really had a conversation about what admin features should be a part of this repo, but I assume we want to keep it to a minimum?

the build looks like it was stopped. Are you confident it is just SSL stuff?

**Comment by mccalluc** [comment]
Decided it's better in a separate project. Will delete branch when done.

**Comment by mccalluc** [comment]
(The script now lives in https://github.com/WGBH/AAPB-etc.)

**Comment by afred** [comment]
👍

**Comment by caseyedavis12** [comment]
@mccalluc: Awesome!

________________________________

**Pull request closed without merging**
