### PR TITLE
Tests are passing for Chuck with this.

### PR DESCRIPTION
**Pull request by mccalluc**
@afred?

### CODE REVIEW

**Comment by afred** [comment]
@mccalluc there might be a bug in the Sony Ci api. Running locally, with proper Ci credentials, I get this error:
```
rspec spec/features/media_spec.rb:34
Run options: include {:locations=>{"./spec/features/media_spec.rb"=>[34]}}

Media
  redirects as expected (FAILED - 1)

Failures:

  1) Media redirects as expected
     Failure/Error: ci = SonyCiAdmin.new(credentials_path: credentials_path)
     RuntimeError:
       Expected ["client_id", "client_secret", "password", "username", "workspace_id"] in ci credentials, not ["client_id", "client_secret", "password", "username"]
     # /Users/andrew_myers/.rvm/gems/ruby-2.0.0-p353/gems/sony-ci-api-0.0.2/lib/sony-ci-api/sony_ci_basic.rb:23:in `block in initialize'
     # /Users/andrew_myers/.rvm/gems/ruby-2.0.0-p353/gems/sony-ci-api-0.0.2/lib/sony-ci-api/sony_ci_basic.rb:21:in `tap'
     # /Users/andrew_myers/.rvm/gems/ruby-2.0.0-p353/gems/sony-ci-api-0.0.2/lib/sony-ci-api/sony_ci_basic.rb:21:in `initialize'
     # ./spec/features/media_spec.rb:10:in `new'
     # ./spec/features/media_spec.rb:10:in `safe_ci'
     # ./spec/features/media_spec.rb:35:in `block (2 levels) in <top (required)>'
```

**Comment by afred** [comment]
^ or rather... the AAPB code is not using the Sony Ci api in the most up-to-date way.

**Comment by mccalluc** [comment]
@afred: No: it looks like your ci.yml is missing `workspace_id`?

**Comment by afred** [comment]
@mccalluc hmm... ok. I pulled my `ci.yml` from production. So this would result in errors on production, yes? I would think it is causing a problem already, unless production is somehow running an older version of the Sony Ci api.. or if the error is getting gobbled in the production environment?

**Comment by afred** [comment]
Sony Ci API issues seems to be unrelated to these changes. Opened #910 to address it. Merging this one.

**Pull request merged**
