### PR TITLE
Create donate.md

### PR DESCRIPTION
**Pull request by mccalluc**
@caseyedavis12 : do you want this merged? I'll go ahead and add the header link on this branch, too, if that's ok.

### CODE REVIEW

**Comment by caseyedavis12** [comment]
@mccalluc: I just added the Kimbia script to the donate.md page. I am leaving the branch open in case you want to include the header edits in this branch. Do you also want to make the css edits to the form in this branch similar to what you did on Open Vault?

**Comment by caseyedavis12** [comment]
PING @mccalluc:  am leaving the branch open in case you want to include the header edits in this branch. Do you also want to make the css edits to the form in this branch similar to what you did on Open Vault?

**Comment by mccalluc** [comment]
Thanks. Just getting back to this: I'll put a screen shot up in a bit.

**Comment by mccalluc** [comment]
screen shot 2016-05-19 at 11 52 42 am

**Comment by caseyedavis12** [comment]
@mccalluc: looks awesome!

<http://www.americanarchivepb.wordpress.com>

________________________________

**Comment by mccalluc** [comment]
screen shot 2016-05-19 at 12 04 45 pm

**Comment by caseyedavis12** [comment]
@mccalluc: Great.

<http://www.americanarchivepb.wordpress.com>

________________________________

**Comment by mccalluc** [comment]
@caseyedavis12 : if this looks good go ahead and merge. (Besides the tabs and the bounding box, I lightened the font to match the rest of the page.) Fixes #941 / #942.

screen shot 2016-05-19 at 12 42 35 pm
screen shot 2016-05-19 at 12 43 08 pm

**Comment by caseyedavis12** [comment]
@mccalluc: Did I merge this correctly?

**Comment by mccalluc** [comment]
@caseyedavis12 : yep! (you can also delete the branch after a merge.)

If the merge is at all complicated because of conflicts, github will tell you it needs to be done on the commandline, so there's not that much that can go wrong here. (famous last words)

**Pull request merged**
