### PR TITLE
Pull-left every image. Fix #746.

### LINKED ISSUE #746: Wrap text around images on About pages
When images are included within the text on the about/projects and about/funding pages, please wrap text around the images.

### PR DESCRIPTION
**Pull request by mccalluc**
@afred? Might also want to add some padding on the right? Maybe a new class just for these images?

### CODE REVIEW

**Comment by afred** [comment]
@mccalluc i would favor a custom class to which we could apply `pull-left`, `padding`, et. al. in SASS as opposed to in the model.

**Comment by mccalluc** [comment]
@afred : per Casey's comment, I'm not sure this is even what we want. On the agenda for the next meeting?

**Comment by afred** [comment]
@mccalluc sounds good

**Comment by afred** [comment]
@caseyedavis12 we forgot to discuss this in the meeting. As @mccalluc points out, this PR is for a default behavior. The options for a default behavior include:
  * align all images to the left (this PR)
  * align all images to the right
  * alternate between align left and right, starting with the left
  * alternate between align left and right, starting with the right

If you want finer grained control on a per-image basis, you can embed your own HTML as @mccalluc says. However this is hacky, and should not be done very much, if at all. If we find ourselves embedding HTML within the markdown more than once or twice, then it's time to reevaluate our approach.

**Comment by caseyedavis12** [comment]
@afred: can I see a screenshot of what the images on On Location Research look like aligned left?


cc @mccalluc

**Comment by afred** [comment]
@caseyedavis12 sure, stand by.

**Comment by afred** [comment]
@caseyedavis12 
image

**Comment by caseyedavis12** [comment]
@afred :thumbsup:

**Comment by afred** [comment]
@mccalluc latest commit on the PR does a small refactor. Please review.

**Comment by afred** [comment]
@mccalluc ping. Please review the last commit and merge if ok. Thanks!

**Comment by mccalluc** [comment]
@afred: nope: This interacts badly with the header: 
- Something is adding padding above the banner.
- and we're losing the padding below the banner, too.
screen shot 2015-11-09 at 10 57 33 am

**Comment by afred** [comment]
@mccalluc ah, good eye. Please review latest PR and merge if ok.

I think these look pretty good. They also align the top of the banner with the top of the left menu, which wasn't happening before.

1. **Banner w/ subsequent images left-aligned by default**
image

1. **Banner followed by blockquote (which has a `margin-top`)**
image

1. **Banner followed by paragraph**
image

1. **Banner followed by left-aligned image + paragraph**
image

1. **Banner followed by H2 heading**
image

**Comment by caseyedavis12** [comment]
@mccalluc, thanks for catching that. the screenshots that @afred posted look good to me.

**Comment by mccalluc** [comment]
@caseyedavis12 : note that the spacing between quotes and citations has changed. Still think it's good enough? (For what it's worth, I think the space before might have been too much.)
screen shot 2015-11-10 at 10 32 44 am

**Comment by caseyedavis12** [comment]
@mccalluc: I agree. I like the new version with less space better.

**Pull request merged**
