### PR TITLE
Advanced search again 478

### PR DESCRIPTION
**Pull request by mccalluc**
Looking at this, I should add some tests, but wanted to confirm that this is what folks imagined. @caseyedavis12 / @sroosa?

screen shot 2015-07-28 at 4 35 04 pm

### CODE REVIEW

**Comment by caseyedavis12** [comment]
This is awesome.


The only thing I see that maybe @hammicakes can work on is that now the search bar in the header is really close to the logo.

**Comment by mccalluc** [comment]
Thanks! hmm... Way back when we reduced the vertical spacing above the logo to fit more on the page. options:
- undo that tweak.
- make the search box not as wide.
- Something shorter than "Advanced Search..."
- Do nothing: This was a particularly small window, just for the screenshot.

Glad to defer to someone else, but I don't think that needs to block merge.

**Comment by caseyedavis12** [comment]
@mccalluc: Ok, I didn't realize that the screenshot was a small window. I vote for:

  *   Do nothing: This was a particularly small window, just for the screenshot.

**Comment by mccalluc** [comment]
Thinking about it overnight, the UI is fine, but the query construction would be better done on the server: 
- No dependence on JS.
- Less testing overhead.
(Closing, but will keep the branch until I'm sure the other way will work.)

**Pull request closed without merging**
