### PR TITLE
Fix #353.

### LINKED ISSUE #353: License
You all deserve a lot of credit for working out in the open on GitHub. Have you thought about adding a license to the code?

### PR DESCRIPTION
**Pull request by mccalluc**
(VideoJS is missing, but IANAL.)

### CODE REVIEW

**Comment by caseyedavis12** [comment]
@mccalluc: that's my fault for missing videojs. Can you add

Video.js — Apache License Version 2.0 (https://github.com/videojs/video.js/blob/master/LICENSE)

**Comment by mccalluc** [comment]
For that matter:
- We use the PBCore schema without the attribution statement required on http://pbcore.org/terms-and-conditions/
- Jetty
- I have no idea what the rights situation is regarding the background images which we have checked in
- It's small, but I suppose there is a copyright on the sample data that is checked in. Do we worry about that? 

What are the guiding principles going forward?
- Should I change the licence on sony-ci-api to Apache?
- If I include code from another project keeping its header license info, is that enough, or does everything get added to this list.

**Comment by afred** [comment]
@mccalluc feel free to merge when @caseyedavis12 finalizes

**Comment by afred** [comment]
@caseyedavis12 re-pinging you on this just to let you know I was going to wait for answers to @mccalluc  questions above before merging. Thanks!

**Comment by mccalluc** [comment]
@afred: This is ready to go. None of the points I had above are relevant for getting this merged.

**Pull request merged**
