### PR TITLE
Update ruby version

### PR DESCRIPTION
**Pull request by mccalluc**
@caseyedavis12 : Keeping versions up to date is a good thing, but sometimes dependencies haven't kept up. Do we believe that gallery remains important? It might be a quick fix, or it might not, but if it's not essential, dropping it would be the easiest solution.

Towards #943.

### CODE REVIEW

**Comment by caseyedavis12** [comment]
@mccalluc: Do you mean that with this ruby update, we lose the Gallery view on AAPB unless further steps are taken to re-implement? Would a curated exhibit section just use the list view below the narrative?

________________________________

**Comment by mccalluc** [comment]
Casie is ok with dropping gallery.

**Comment by afred** [comment]
@mccalluc what was the answer to @caseyedavis12's question?.. i.e .what does "dropping the gallery" imply?

**Comment by afred** [comment]
@mccalluc there appear to be failures other than the SSL issue

**Comment by mccalluc** [comment]
@afred: I'm a bit perturbed by the apparent change in the DOM structure that Capybara is now seeing: it seems to think there's something like an empty element, but when I inspect the html source, I don't see what it's seeing.

Any other thoughts?

**Pull request merged**
