### PR TITLE
Presidential elections

### PR DESCRIPTION
**Pull request by caseyedavis12**
We're ready to merge and deploy. @sroosa has the list of GUIDs to reindex.

### CODE REVIEW

**Comment by afred** [comment]
I'm adding a bit to even out the carousel, so we can get all of them in there, while not leaving empty spaces. Stand by...

**Comment by afred** [comment]
@mccalluc?

**Comment by mccalluc** [comment]
@afred: I'll try to fix the test and will review the substance.

**Comment by afred** [comment]
the PR is intended to avoid this situation...

image

**Comment by mccalluc** [comment]
@caseyedavis12 : footnotes on http://localhost:3000/exhibits/presidential-elections/candidates point to http://localhost:3000/exhibits/presidential-elections/notes#7, but there doesn't seem to actually be a matching anchor on that page?

**Comment by caseyedavis12** [comment]
@mccalluc: Does the anchor on the notes page need to look like


```<a name="7"></a><sup>7</sup>```


or


```<a name="#7"></a><sup>7</sup>```

**Comment by mccalluc** [comment]
@caseyedavis12 : the former: `<a name="7"></a><sup>7</sup>`

The "#" is punctuation in the URL. Also, that will will, but if anything else on the page happens to have an id that's just a number, your links will break. Safer, as we discussed, to use some consistent prefix in your anchors. (But again, that's just future-proofing.)

**Comment by mccalluc** [comment]
The notes page isn't working because the content hasn't been put in a section, and so it ends up inheriting content from the top page: ie, there's content on the page, just not the content we want. I'll fix. @caseyedavis12 : this explains the broken links.

**Comment by afred** [comment]
@mccalluc the broken tests are due to `api.js` returning 1 fewer results that expected. However, looking at the tests, it's unclear to me whether this is really an introduced bug, or whether the tests just need to be adjusted.

**Comment by afred** [comment]
@mccalluc hmm.. so now I'm confused as to what was causing [this failure](https://travis-ci.org/WGBH/AAPB2/builds/106259299)?

**Comment by caseyedavis12** [comment]
@mccalluc: Does content in exhibit sections have to be in the Online Reading Room


There is one program that is not yet in the online reading room that is linked in an exhibit section. I am waiting on approval. I can remove it if that will fix the issue.

**Comment by caseyedavis12** [comment]
@mccalluc: This is the program for which I am waiting approval:
cpb-aacip/15-st7dr2pn78

**Comment by afred** [comment]
Ugh... failures due to a connection timeout error w/ Solr. Trying again.

**Comment by afred** [comment]
passing! [see this](https://travis-ci.org/WGBH/AAPB2/builds/106267698)

merging!!

**Pull request merged**
