### PR TITLE
Bullets align better, and the banner is still at the top, but ...

### LINKED ISSUE #874: Bullet points on /projects/permanent-entity
The bullet points on the /projects/permanent-entity page are not in alignment with the beginning of each statement in the list.

Done when: bullet points are aligned with the beginning of each statement in the list.

### PR DESCRIPTION
**Pull request by mccalluc**
but not sure this is a good approach. Fix #874, perhaps. @afred?

### CODE REVIEW

**Comment by mccalluc** [comment]
@afred. ping?

**Comment by caseyedavis12** [comment]
@mccalluc, will this fix the bullet alignment on the Mission and Vision page? http://americanarchive.org/about-the-american-archive/vision-and-mission

**Comment by afred** [comment]
@caseyedavis12, below is a screenshot of what I'm seeing. Not sure what you mean by aligning the bullet points with the first statement in the list. Do you want the space above the bullet list reduced? Please advise? (p.s. sorry it's take this long to get to this PR)

image

**Comment by afred** [comment]
ah... i think this PR may have been superseded by another. Adding the `margin-top: -15px` from the PR causes a misalignment...

**without this PR, the banner image is aligned correctly...**
image



**with this PR, the banner image gets misaligned...**
image


Closing this. If I'm missing something @mccalluc, @caseyedavis12, feel free to re-open it.

**Pull request closed without merging**
