### PR TITLE
adds title lists and links to them from main page

### PR DESCRIPTION
**Pull request by sroosa**

### CODE REVIEW

**Comment by sroosa** [comment]
I just realized that the links at the bottom of the main page don't work. Oops. Will fix now.

**Comment by sroosa** [comment]
made some last minutes fixes. should be good to go, i believe.

**Comment by afred** [comment]
@sroosa it should be `<br />` and not `</br>` for your HTML breaks

**Comment by sroosa** [comment]
@afred Whoops! good catch! All fixed now.

**Pull request merged**
