### PR TITLE
Fixes #411, maybe

### LINKED ISSUE #411: New section on Homepage
In addition to the new Curated Exhibitions section on the homepage, we would like an additional section featuring the Every Picture Tells a Story clip reel, which is currently on the About page.

### PR DESCRIPTION
**Pull request by mccalluc**
@caseyedavis12 :
- Does it need a new background image?
- Does it belong at the bottom?
- Does it need a title?
- Should the video on "about" be removed?

### CODE REVIEW

**Comment by caseyedavis12** [comment]
Can I see a screenshot of what it looks like on your local machine?

**Comment by mccalluc** [comment]
@caseyedavis12 :

screen shot 2015-05-15 at 1 42 25 pm

**Comment by caseyedavis12** [comment]
Awesome! Can you add a background color to the section that is in our color palette? I'm thinking 144,42,141 or 158,32,100.

It would be good if we could replace the video on the About Us page with a banner image, but that needs to be identified. If Sadie doesn't have time to find a banner image now, we can leave the video on the About Us page for now.

Could you add a title header to this section saying "Every Picture Tells a Story" (following same format as the "Participating Organizations" section
Under the title, could you add text that says "Watch a five minute introduction to the treasures of public broadcasting, written and produced by Elizabeth Deane"

(P.S. -- I will remove the "Every Picture Tells a Story" text from the play on Vimeo.)

Thank you!!!
[cid:E007831D-DA01-402C-B013-7FEE9ECC70D1]

**Comment by caseyedavis12** [comment]
screen shot 2015-05-15 at 1 49 05 pm

**Comment by caseyedavis12** [comment]
For the title in the new section, please keep "Every Picture Tells a Story" in quotes. Thanks!

**Pull request merged**
